name: reviewblog
description: A Flutter blog application with Supabase integration demonstrating lifecycle methods.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

